package com.trials.javacallfromdmn;

import com.trials.javacallfromdmn.CurrencyDTO;

import java.util.ArrayList;
import java.util.List;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class HolidayDTO {

    private String calendarDate;
	
	List<CurrencyDTO> currencies = new ArrayList<>();

	public String getCalendarDate() {
		return calendarDate;
	}

	public void setCalendarDate(String calendarDate) {
		this.calendarDate = calendarDate;
	}

	public List<CurrencyDTO> getCurrencies() {
		return currencies;
	}

	public void setCurrencies(List<CurrencyDTO> currencies) {
		this.currencies = currencies;
	}



}