package com.trials.javacallfromdmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HolidayDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HolidayDTO() {
    }




}