package com.trials.javacallfromdmn;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JavaClass {

   public static String hello(String name){
       return "hello " + name;
   }
   
   
    public static List<String> helloMore(String name){
        List<String> list = new ArrayList<>();
        list.add("h1");
        list.add("h2");
       return list;
   }



}