package com.trials.javacallfromdmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JavaClass {

   public static String hello(String name){
       return "hello " + name;
   }



}